version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/manager"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/manager"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gomod"
    directory: "/worker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/worker"
    schedule:
      interval: "weekly"
