server:
  port: 8080
  env: dev
worker:
  addresses:
    - http://crack-hash-worker-1:8080
    - http://crack-hash-worker-2:8080
    - http://crack-hash-worker-3:8080
  health:
    path: /api/worker/health/readiness
    interval: 10s
    timeout: 1m
    retries: 3
task:
  split:
    strategy: chunk-based
    chunkSize: 10000000
  timeout: 1h
  limit: 10
  maxAge: 24h
  finishDelay: 1m
