version: 2
project_name: crack-hash
builds:
  - id: manager
    dir: ./manager
    binary: manager
    main: ./cmd/cli
    ldflags:
      - -s
      - -w
      - -X github.com/ptrvsrg/crack-hash/manager/internal/version.AppVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
  - id: worker
    dir: ./worker
    binary: worker
    main: ./cmd/cli
    ldflags:
      - -s
      - -w
      - -X github.com/ptrvsrg/crack-hash/worker/internal/version.AppVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - id: manager-archive
    builds:
      - manager
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE.md
  - id: worker-archive
    builds:
      - worker
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE.md
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto