version: "3.8"

name: "crack-hash"

volumes:
  nginx-logs:

networks:
  crack-hash-net:

services:
  manager:
    build:
      context: .
      dockerfile: manager/Dockerfile
      args:
        ARTIFACT_VERSION: ${ARTIFACT_VERSION:-0.0.0}
    image: manager:${ARTIFACT_VERSION:-latest}
    container_name: manager
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "/app/manager healthcheck" ]
    environment:
      SERVER_ENV: prod
      WORKER_ADDRESS: "worker:8080"
    networks:
      - crack-hash-net
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200M"
        reservations:
          cpus: "0.1"
          memory: "100M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      args:
        ARTIFACT_VERSION: ${ARTIFACT_VERSION:-0.0.0}
    image: worker:${ARTIFACT_VERSION:-latest}
    container_name: worker
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "/app/worker healthcheck" ]
    environment:
      SERVER_ENV: prod
      MANAGER_ADDRESS: "manager:8080"
    networks:
      - crack-hash-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "150M"
        reservations:
          cpus: "0.5"
          memory: "75M"
    logging:
      driver: "json-file"  
      options:
        max-size: "10m"    
        max-file: "3"

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -T5 -qO-  http://127.0.0.1:80/api/gateway/status || exit 1" ]
    volumes:
      - ./deploy/api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx:ro
    ports:
      - "8080:80"
    networks:
      - crack-hash-net
    depends_on:
      manager:
        condition: service_healthy
      worker:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20M"
        reservations:
          cpus: "0.02"
          memory: "10M"