version: "3.8"

name: "crack-hash"

volumes:
  nginx-logs:

networks:
  net:

services:
  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      args:
        ARTIFACT_VERSION: ${ARTIFACT_VERSION:-0.0.0}
    image: ghcr.io/ptrvsrg/crack-hash:worker-${ARTIFACT_VERSION:-latest}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "/app/worker healthcheck" ]
    volumes:
      - ./deploy/config/worker/config.yaml:/app/config/config.yaml:ro
    networks:
      - net
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "2.0"
          memory: "150M"
        reservations:
          cpus: "1.0"
          memory: "75M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  manager:
    build:
      context: .
      dockerfile: manager/Dockerfile
      args:
        ARTIFACT_VERSION: ${ARTIFACT_VERSION:-0.0.0}
    image: ghcr.io/ptrvsrg/crack-hash:manager-${ARTIFACT_VERSION:-latest}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "/app/manager healthcheck" ]
    volumes:
      - ./deploy/config/manager/config.yaml:/app/config/config.yaml:ro
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200M"
        reservations:
          cpus: "0.1"
          memory: "100M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      worker:
        condition: service_healthy

  api-gateway:
    image: nginx:1.27.4-alpine3.21
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -T5 -qO-  http://127.0.0.1:80/api/gateway/status || exit 1" ]
    volumes:
      - ./deploy/config/api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx:ro
    ports:
      - "8080:80"
    networks:
      - net
    depends_on:
      manager:
        condition: service_healthy
      worker:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20M"
        reservations:
          cpus: "0.02"
          memory: "10M"