version: "3.8"

name: "crack-hash-dev"

services:
  rabbitmq1:
    ports:
      - '5672:5672'
      - '15672:15672'
  rabbitmq2:
    ports:
      - '5673:5672'
      - '15673:15672'
  rabbitmq3:
    ports:
      - '5674:5672'
      - '15674:15672'
  mongo1:
    ports:
      - '27017:27017'
    networks:
      net:
        ipv4_address: 172.28.0.10
  mongo2:
    ports:
      - '27018:27017'
    networks:
      net:
        ipv4_address: 172.28.0.11
  mongo3:
    ports:
      - '27019:27017'
    networks:
      net:
        ipv4_address: 172.28.0.12
  mongo-express:
    ports:
      - '8081:8081'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24