repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: nixys
    url: https://registry.nixys.io/chartrepo/public

environments:
  dev:
    values:
      - charts:
          versions:
            mongodb: 16.4.7
            rabbitmq: 15.3.3
      - apps:
          - mongodb
          - rabbitmq
  stable:
    values:
      - charts:
          versions:
            mongodb: 16.4.7
            rabbitmq: 15.3.3
            manager: v2.8.3
            worker: v2.8.3
      - apps:
          - mongodb
          - rabbitmq
          - manager
          - worker
---
bases:
  { { - range .Values.apps } }
  - releases/{{ . }}.yaml
  { { - end } }