server:
  port: 8080
  env: dev
mongodb:
  uri:
  username:
  password:
  db:
  writeconcern:
    w: majority
    journal:
  readconcern:
    level: majority
amqp:
  uris:
  username:
  password:
  prefetch: 20
  consumers:
    taskresult:
      queue:
  publishers:
    taskstarted:
      exchange:
      routingkey:
task:
  alphabet: abcdefghijklmnopqrstuvwxyz0123456789
  split:
    strategy: chunk-based
    chunksize: 10000000
  timeout: 1h
  limit: 10
  maxage: 24h
  finishdelay: 1m