// Code generated by mockery v2.53.3. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HealthMock is an autogenerated mock type for the Health type
type HealthMock struct {
	mock.Mock
}

type HealthMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthMock) EXPECT() *HealthMock_Expecter {
	return &HealthMock_Expecter{mock: &_m.Mock}
}

// Health provides a mock function with given fields: ctx
func (_m *HealthMock) Health(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HealthMock_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type HealthMock_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HealthMock_Expecter) Health(ctx interface{}) *HealthMock_Health_Call {
	return &HealthMock_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *HealthMock_Health_Call) Run(run func(ctx context.Context)) *HealthMock_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HealthMock_Health_Call) Return(_a0 error) *HealthMock_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthMock_Health_Call) RunAndReturn(run func(context.Context) error) *HealthMock_Health_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthMock creates a new instance of HealthMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthMock {
	mock := &HealthMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
