with-expecter: true
issue-845-fix: true
resolve-type-alias: false
mockname: "{{.InterfaceName}}Mock"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "mock"
dir: "{{.InterfaceDir}}/mock"
packages:
  github.com/ptrvsrg/crack-hash/commonlib/bus/amqp/publisher:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"