server:
  port: 8080
  env: dev
amqp:
  uris:
  username:
  password:
  prefetch: 10
  consumers:
    taskstarted:
      queue:
  publishers:
    taskresult:
      exchange:
      routingkey:
task:
  split:
    strategy: chunk-based
    chunk-size: 10000000
  progressPeriod: 5s