server:
  port: 8080
  env: dev
  cors:
    allowedOrigins:
      - "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowedHeaders:
      - "*"
    allowCredentials: false
    maxAge: 24h
amqp:
  uris:
  username:
  password:
  prefetch: 10
  consumers:
    taskstarted:
      queue:
  publishers:
    taskresult:
      exchange:
      routingkey:
task:
  split:
    strategy: chunk-based
    chunk-size: 10000000
  progressPeriod: 5s