version: "3.8"

x-rabbitmq-defaults: &rabbitmq-defaults
  image: 'rabbitmq:4.0.6-management-alpine'
  restart: unless-stopped
  healthcheck:
    test: [ "CMD-SHELL", "rabbitmq-diagnostics -q check_port_connectivity && rabbitmq-diagnostics -q cluster_status && rabbitmq-diagnostics -q check_local_alarms" ]
  volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    - rabbitmq-logs:/var/log/rabbitmq
    - ./envs/${ENVIRONMENT:-stable}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    - ./envs/${ENVIRONMENT:-stable}/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  networks:
    - net
  deploy:
    resources:
      limits:
        cpus: "1.5"
        memory: "1536M"
      reservations:
        cpus: "0.5"
        memory: "512M"

x-rabbitmq-defaults-environment: &rabbitmq-defaults-environment
  RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-secret}

services:
  rabbitmq1:
    <<: *rabbitmq-defaults
    hostname: rabbitmq1
    environment:
      <<: *rabbitmq-defaults-environment
      NODENAME: rabbitmq@rabbitmq1
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
      - rabbitmq1-logs:/var/log/rabbitmq
      - ./envs/${ENVIRONMENT:-stable}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./envs/${ENVIRONMENT:-stable}/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  rabbitmq2:
    <<: *rabbitmq-defaults
    hostname: rabbitmq2
    environment:
      <<: *rabbitmq-defaults-environment
      NODENAME: rabbitmq@rabbitmq2
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq
      - rabbitmq2-logs:/var/log/rabbitmq
      - ./envs/${ENVIRONMENT:-stable}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./envs/${ENVIRONMENT:-stable}/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  rabbitmq3:
    <<: *rabbitmq-defaults
    hostname: rabbitmq3
    environment:
      <<: *rabbitmq-defaults-environment
      NODENAME: rabbitmq@rabbitmq3
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
      - rabbitmq3-logs:/var/log/rabbitmq
      - ./envs/${ENVIRONMENT:-stable}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./envs/${ENVIRONMENT:-stable}/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

volumes:
  rabbitmq1-data:
  rabbitmq2-data:
  rabbitmq3-data:
  rabbitmq1-logs:
  rabbitmq2-logs:
  rabbitmq3-logs: