version: "3.8"

services:
  reverse-proxy:
    image: nginx:1.27.4-alpine3.21
    restart: unless-stopped
    entrypoint: ""
    healthcheck:
      test: [ "CMD-SHELL", "wget -T5 -qO-  http://127.0.0.1:80/proxy/status || exit 1" ]
    volumes:
      - ./envs/${ENVIRONMENT:-stable}/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx:ro
    ports:
      - "8080:80"
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20M"
        reservations:
          cpus: "0.02"
          memory: "10M"
    depends_on:
      mongo-express:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy
      worker:
        condition: service_healthy
      manager:
        condition: service_healthy

volumes:
  nginx-logs: