version: "3.8"

services:
  worker:
    build:
      context: ../..
      dockerfile: worker/Dockerfile
      args:
        ARTIFACT_VERSION: ${WORKER_ARTIFACT_VERSION:-latest}
    image: ghcr.io/ptrvsrg/crack-hash:worker-${WORKER_ARTIFACT_VERSION:-latest}
    restart: unless-stopped
    environment:
      AMQP_USERNAME: ${RABBITMQ_USERNAME:-admin}
      AMQP_PASSWORD: ${RABBITMQ_PASSWORD:-password}
    healthcheck:
      test: [ "CMD-SHELL", "/app/worker healthcheck" ]
    volumes:
      - ./envs/${ENVIRONMENT:-stable}/worker/config.yaml:/app/config/config.yaml:ro
    networks:
      - net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: "150M"
        reservations:
          cpus: "1.0"
          memory: "75M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy