name: Test - WEB
on:
  push:
    paths:
      - 'web/**'
  pull_request:
    paths:
      - 'web/**'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.6.0
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
          dir: web
      - name: Upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: web/node_modules
  lint:
    needs: dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.6.0
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: web/node_modules
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: global add eslint
          dir: web
      - name: ESLint
        uses: sibiraj-s/action-eslint@v3
        with:
          working-directory: web
          ignore-path: web/.gitignore
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.6.0
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: web/node_modules
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: global add vite
          dir: web
      - name: Build
        env:
          NODE_ENV: production
        working-directory: web
        run: vite build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: web/dist